/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bootstrap Admin */
        post: operations["bootstrap_admin_api_admin_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User Status */
        patch: operations["update_user_status_api_admin_users__user_id__status_patch"];
        trace?: never;
    };
    "/api/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Events */
        get: operations["list_audit_events_api_admin_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_datasets_get"];
        put?: never;
        /** Create Dataset */
        post: operations["create_dataset_api_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/preprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preprocess Dataset */
        post: operations["preprocess_dataset_api_datasets__dataset_id__preprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dataset Segments */
        get: operations["list_dataset_segments_api_datasets__dataset_id__segments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/segments/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Review Dataset Segment */
        patch: operations["review_dataset_segment_api_datasets__dataset_id__segments__segment_id__patch"];
        trace?: never;
    };
    "/api/datasets/{dataset_id}/segments/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Dataset Segments */
        post: operations["confirm_dataset_segments_api_datasets__dataset_id__segments_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Voice Profiles */
        get: operations["list_voice_profiles_api_voices_get"];
        put?: never;
        /** Create Voice Profile */
        post: operations["create_voice_profile_api_voices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices/{profile_id}/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Voice Reference */
        post: operations["add_voice_reference_api_voices__profile_id__references_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices/{profile_id}/references/{reference_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Voice Reference */
        delete: operations["delete_voice_reference_api_voices__profile_id__references__reference_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices/{profile_id}/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train Voice Profile */
        post: operations["train_voice_profile_api_voices__profile_id__train_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Voice Profile */
        get: operations["get_voice_profile_api_voices__profile_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/segments/{segment_id}/emotion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Override Emotion */
        put: operations["override_emotion_api_datasets__dataset_id__segments__segment_id__emotion_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/syntheses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Syntheses */
        get: operations["list_syntheses_api_syntheses_get"];
        put?: never;
        /** Create Synthesis */
        post: operations["create_synthesis_api_syntheses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/syntheses/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Synthesis */
        get: operations["get_synthesis_api_syntheses__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/syntheses/{job_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Synthesis Audio */
        get: operations["get_synthesis_audio_api_syntheses__job_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/safety/detect-watermark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detect Watermark */
        post: operations["detect_watermark_api_safety_detect_watermark_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voices/{profile_id}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Voice */
        post: operations["evaluate_voice_api_voices__profile_id__evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Profile */
        get: operations["get_my_profile_api_users_me_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Profile */
        patch: operations["update_my_profile_api_users_me_profile_patch"];
        trace?: never;
    };
    "/api/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload My Avatar */
        post: operations["upload_my_avatar_api_users_me_avatar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/avatars/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Avatar */
        get: operations["get_avatar_api_avatars__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unread Count */
        get: operations["unread_count_api_notifications_unread_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/mark-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_api_notifications_mark_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plaza/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Posts */
        get: operations["list_posts_api_plaza_posts_get"];
        put?: never;
        /** Publish Post */
        post: operations["publish_post_api_plaza_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plaza/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Comments */
        get: operations["my_comments_api_plaza_comments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plaza/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post */
        get: operations["get_post_api_plaza_posts__post_id__get"];
        put?: never;
        post?: never;
        /** Delete Post */
        delete: operations["delete_post_api_plaza_posts__post_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plaza/posts/{post_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Comments */
        get: operations["list_comments_api_plaza_posts__post_id__comments_get"];
        put?: never;
        /** Add Comment */
        post: operations["add_comment_api_plaza_posts__post_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plaza/posts/{post_id}/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Like Post */
        post: operations["like_post_api_plaza_posts__post_id__likes_post"];
        /** Unlike Post */
        delete: operations["unlike_post_api_plaza_posts__post_id__likes_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plaza/posts/{post_id}/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Favorite Post */
        post: operations["favorite_post_api_plaza_posts__post_id__favorites_post"];
        /** Unfavorite Post */
        delete: operations["unfavorite_post_api_plaza_posts__post_id__favorites_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plaza/posts/{post_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Package */
        get: operations["download_package_api_plaza_posts__post_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plaza/posts/{post_id}/download/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Reference */
        get: operations["download_reference_api_plaza_posts__post_id__download_reference_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plaza/posts/{post_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Reference */
        get: operations["preview_reference_api_plaza_posts__post_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plaza/posts/{post_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Post */
        post: operations["import_post_api_plaza_posts__post_id__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminUserListResponse */
        AdminUserListResponse: {
            /** Items */
            items: components["schemas"]["AdminUserSummary"][];
        };
        /** AdminUserSummary */
        AdminUserSummary: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "admin";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "disabled";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dataset Count */
            dataset_count: number;
            /** Voice Count */
            voice_count: number;
            /** Job Count */
            job_count: number;
        };
        /** AuditEventListResponse */
        AuditEventListResponse: {
            /** Items */
            items: components["schemas"]["AuditEventSummary"][];
            /** Next Before Id */
            next_before_id: number | null;
        };
        /** AuditEventSummary */
        AuditEventSummary: {
            /** Id */
            id: number;
            /** Event Type */
            event_type: string;
            /** Subject Id */
            subject_id: string | null;
            /** Metadata */
            metadata: {
                [key: string]: string;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_create_dataset_api_datasets_post */
        Body_create_dataset_api_datasets_post: {
            /** File */
            file: string;
            /**
             * Consent Confirmed
             * @default false
             */
            consent_confirmed: boolean;
        };
        /** Body_upload_my_avatar_api_users_me_avatar_post */
        Body_upload_my_avatar_api_users_me_avatar_post: {
            /** File */
            file: string;
        };
        /**
         * CloudEmotionLabel
         * @enum {string}
         */
        CloudEmotionLabel: "neutral" | "happy" | "angry" | "sad" | "afraid" | "disgusted" | "melancholic" | "surprised" | "calm";
        /** CloudEmotionOptions */
        CloudEmotionOptions: {
            /**
             * Control Mode
             * @default label
             * @enum {string}
             */
            control_mode: "auto" | "label" | "description" | "vector";
            label?: components["schemas"]["CloudEmotionLabel"] | null;
            /** Description */
            description?: string | null;
            /**
             * Emotion Strength
             * @default 0.8
             */
            emotion_strength: number;
            /**
             * Sample Rate
             * @default 44100
             * @enum {integer}
             */
            sample_rate: 22050 | 44100 | 48000;
            /**
             * Speed
             * @default 1
             */
            speed: number;
            /**
             * Gain
             * @default 1
             */
            gain: number;
            /**
             * Use Random
             * @default false
             */
            use_random: boolean;
            /**
             * Interval Silence
             * @default 200
             */
            interval_silence: number;
            /** Emotion Vector */
            emotion_vector?: number[] | null;
            /** Emotion Vector Mode */
            emotion_vector_mode?: ("single" | "mixed") | null;
        };
        /** CredentialsRequest */
        CredentialsRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** DashboardCounts */
        DashboardCounts: {
            /** Datasets */
            datasets: number;
            /** Voices */
            voices: number;
            /** Jobs */
            jobs: number;
            /** Active Jobs */
            active_jobs: number;
            /** Syntheses */
            syntheses: number;
        };
        /** DashboardResponse */
        DashboardResponse: {
            counts: components["schemas"]["DashboardCounts"];
            /** Recent Jobs */
            recent_jobs: components["schemas"]["JobSummary"][];
            /** Voices */
            voices: components["schemas"]["VoiceSummary"][];
            readiness: components["schemas"]["ReadinessSummary"];
        };
        /** DatasetListResponse */
        DatasetListResponse: {
            /** Items */
            items: components["schemas"]["DatasetSummary"][];
        };
        /** DatasetPreprocessResponse */
        DatasetPreprocessResponse: {
            /** Dataset Id */
            dataset_id: string;
            /** Effective Seconds */
            effective_seconds: number;
            /** Status */
            status: string;
            /**
             * Segment Count
             * @default 0
             */
            segment_count: number;
            /** Snr Warning Db */
            snr_warning_db: number;
            /**
             * Warning Codes
             * @default []
             */
            warning_codes: string[];
        };
        /** DatasetSegmentSummary */
        DatasetSegmentSummary: {
            /** Segment Id */
            segment_id: string;
            /** Order Index */
            order_index: number;
            /** Relative Path */
            relative_path: string;
            /** Duration Seconds */
            duration_seconds: number;
            /** Snr Db */
            snr_db: number | null;
            /** Snr Warning Db */
            snr_warning_db: number;
            /**
             * Warning Codes
             * @default []
             */
            warning_codes: string[];
            /** Language */
            language: string;
            /** Split */
            split: string;
            /** Auto Transcript */
            auto_transcript: string;
            /** Manual Transcript */
            manual_transcript: string | null;
            /** Effective Transcript */
            effective_transcript: string;
            /** Transcript Source */
            transcript_source: string;
            /** Auto Emotion Label */
            auto_emotion_label: string | null;
            /** Auto Emotion Confidence */
            auto_emotion_confidence: number | null;
            /** Manual Emotion Label */
            manual_emotion_label: string | null;
            /** Effective Emotion Label */
            effective_emotion_label: string | null;
            /** Emotion Source */
            emotion_source: string;
            /** Review Reason */
            review_reason: string | null;
            /** Reviewed */
            reviewed: boolean;
        };
        /** DatasetSummary */
        DatasetSummary: {
            /** Id */
            id: string;
            /** Authorization Confirmed */
            authorization_confirmed: boolean;
            /** Status */
            status: string;
            /** Effective Seconds */
            effective_seconds: number | null;
            /** Asset Count */
            asset_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EmotionControl */
        EmotionControl: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "auto" | "manual" | "reference";
            label?: components["schemas"]["EmotionLabel"] | null;
            /**
             * Strength
             * @default 0.65
             */
            strength: number;
            /** Reference Audio Id */
            reference_audio_id?: string | null;
        };
        /**
         * EmotionLabel
         * @enum {string}
         */
        EmotionLabel: "neutral" | "happy" | "sad" | "angry" | "fearful" | "disgusted" | "surprised" | "other";
        /** EmotionOverrideRequest */
        EmotionOverrideRequest: {
            label: components["schemas"]["EmotionLabel"];
            /** Reason */
            reason: string;
        };
        /** EvaluationQueuedResponse */
        EvaluationQueuedResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheck */
        HealthCheck: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
        };
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "preprocess" | "train" | "synthesize" | "evaluate";
        /** JobListResponse */
        JobListResponse: {
            /** Items */
            items: components["schemas"]["JobSummary"][];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "canceled";
        /** JobSummary */
        JobSummary: {
            /** Id */
            id: string;
            kind: components["schemas"]["JobKind"];
            status: components["schemas"]["JobStatus"];
            /** Error Code */
            error_code: string | null;
            /** Public Message */
            public_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** LiveResponse */
        LiveResponse: {
            /** Status */
            status: string;
        };
        /** LocalSynthesisOptions */
        LocalSynthesisOptions: {
            /**
             * Cut Method
             * @default none
             * @enum {string}
             */
            cut_method: "none" | "four_sentences" | "fifty_chars" | "zh_period" | "en_period" | "punctuation";
            /**
             * Speed
             * @default 1
             */
            speed: number;
            /**
             * Pause Seconds
             * @default 0.3
             */
            pause_seconds: number;
            /**
             * Top K
             * @default 15
             */
            top_k: number;
            /**
             * Top P
             * @default 1
             */
            top_p: number;
            /**
             * Temperature
             * @default 1
             */
            temperature: number;
        };
        /** MarkReadRequest */
        MarkReadRequest: {
            /** Notification Ids */
            notification_ids?: string[] | null;
            /**
             * All
             * @default false
             */
            all: boolean;
        };
        /** MarkReadResponse */
        MarkReadResponse: {
            /** Updated */
            updated: number;
        };
        /** NotificationListResponse */
        NotificationListResponse: {
            /** Items */
            items: components["schemas"]["NotificationSummary"][];
            /** Total */
            total: number;
        };
        /** NotificationSummary */
        NotificationSummary: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Actor Display Name */
            actor_display_name: string;
            /** Post Id */
            post_id: string;
            /** Voice Name */
            voice_name: string;
            /** Comment Excerpt */
            comment_excerpt: string | null;
            /** Is Read */
            is_read: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PlazaActionResponse */
        PlazaActionResponse: {
            /** Ok */
            ok: boolean;
        };
        /** PlazaAuthorInfo */
        PlazaAuthorInfo: {
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name: string;
            /** Has Avatar */
            has_avatar: boolean;
        };
        /** PlazaCommentCreate */
        PlazaCommentCreate: {
            /** Content */
            content: string;
        };
        /** PlazaCommentListResponse */
        PlazaCommentListResponse: {
            /** Items */
            items: components["schemas"]["PlazaCommentSummary"][];
            /** Total */
            total: number;
        };
        /** PlazaCommentSummary */
        PlazaCommentSummary: {
            /** Id */
            id: string;
            /** Post Id */
            post_id: string;
            author: components["schemas"]["PlazaAuthorInfo"];
            /** Content */
            content: string;
            /** Voice Name */
            voice_name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PlazaDeleteResponse */
        PlazaDeleteResponse: {
            /** Deleted */
            deleted: boolean;
        };
        /** PlazaImportRequest */
        PlazaImportRequest: {
            /**
             * Authorization Confirmed
             * @default false
             */
            authorization_confirmed: boolean;
        };
        /** PlazaImportResponse */
        PlazaImportResponse: {
            /** Voice Profile Id */
            voice_profile_id: string;
            /** Display Name */
            display_name: string;
        };
        /** PlazaPostListResponse */
        PlazaPostListResponse: {
            /** Items */
            items: components["schemas"]["PlazaPostSummary"][];
            /** Total */
            total: number;
        };
        /** PlazaPostSummary */
        PlazaPostSummary: {
            /** Id */
            id: string;
            voice: components["schemas"]["PlazaVoiceInfo"];
            author: components["schemas"]["PlazaAuthorInfo"];
            /** Description */
            description: string | null;
            /** Like Count */
            like_count: number;
            /** Comment Count */
            comment_count: number;
            /** Favorite Count */
            favorite_count: number;
            /** Liked By Me */
            liked_by_me: boolean;
            /** Favorited By Me */
            favorited_by_me: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PlazaPublishRequest */
        PlazaPublishRequest: {
            /** Voice Profile Id */
            voice_profile_id: string;
            /** Description */
            description?: string | null;
        };
        /** PlazaStats */
        PlazaStats: {
            /** Published */
            published: number;
            /** Likes Received */
            likes_received: number;
        };
        /** PlazaVoiceInfo */
        PlazaVoiceInfo: {
            /** Voice Profile Id */
            voice_profile_id: string;
            /** Display Name */
            display_name: string;
            /** Status */
            status: string;
            /** Reference Count */
            reference_count: number;
            /** Reference Emotions */
            reference_emotions: string[];
        };
        /** ReadinessCheckSummary */
        ReadinessCheckSummary: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
        };
        /** ReadinessSummary */
        ReadinessSummary: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["ReadinessCheckSummary"];
            };
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["HealthCheck"];
            };
        };
        /** SegmentConfirmRequest */
        SegmentConfirmRequest: {
            /** Reason */
            reason: string;
        };
        /** SegmentListResponse */
        SegmentListResponse: {
            /** Dataset Id */
            dataset_id: string;
            /** Status */
            status: string;
            /** Total Segments */
            total_segments: number;
            /** Reviewed Segments */
            reviewed_segments: number;
            /** Effective Seconds */
            effective_seconds: number | null;
            /** Reviewed Effective Seconds */
            reviewed_effective_seconds: number;
            /** Ready For Profile */
            ready_for_profile: boolean;
            /** Items */
            items: components["schemas"]["DatasetSegmentSummary"][];
        };
        /** SegmentReviewRequest */
        SegmentReviewRequest: {
            /** Transcript */
            transcript?: string | null;
            emotion_label?: components["schemas"]["EmotionLabel"] | null;
            /** Language */
            language?: ("zh" | "en") | null;
            /** Reason */
            reason: string;
        };
        /** SynthesisCreate */
        SynthesisCreate: {
            /** Voice Profile Id */
            voice_profile_id: string;
            /** Text */
            text: string;
            /**
             * Text Lang
             * @enum {string}
             */
            text_lang: "zh" | "en" | "ja" | "es" | "ar";
            emotion: components["schemas"]["EmotionControl"];
            /**
             * Consent Confirmed
             * @constant
             */
            consent_confirmed: true;
            /**
             * Synthesis Mode
             * @default local
             * @enum {string}
             */
            synthesis_mode: "local" | "emotion_api";
            local_options?: components["schemas"]["LocalSynthesisOptions"];
            cloud_options?: components["schemas"]["CloudEmotionOptions"] | null;
            /**
             * Cloud Processing Confirmed
             * @default false
             */
            cloud_processing_confirmed: boolean;
        };
        /** SynthesisListResponse */
        SynthesisListResponse: {
            /** Items */
            items: components["schemas"]["SynthesisSummary"][];
        };
        /** SynthesisQueuedResponse */
        SynthesisQueuedResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @constant
             */
            status: "queued";
        };
        /** SynthesisSummary */
        SynthesisSummary: {
            /** Job Id */
            job_id: string;
            /** Voice Profile Id */
            voice_profile_id: string | null;
            /** Text Lang */
            text_lang: ("zh" | "en") | null;
            status: components["schemas"]["JobStatus"];
            /** Download Ready */
            download_ready: boolean;
            /** Watermark Probability */
            watermark_probability: number | null;
            /** Fingerprint Anomaly */
            fingerprint_anomaly: boolean | null;
            /** Speaker Similarity */
            speaker_similarity?: number | null;
            /**
             * Quality Warning Codes
             * @default []
             */
            quality_warning_codes: string[];
            /** Progress Message */
            progress_message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UnreadCountResponse */
        UnreadCountResponse: {
            /** Count */
            count: number;
        };
        /** UserProfileResponse */
        UserProfileResponse: {
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Bio */
            bio: string | null;
            /** Has Avatar */
            has_avatar: boolean;
            stats: components["schemas"]["PlazaStats"];
        };
        /** UserProfileUpdate */
        UserProfileUpdate: {
            /** Display Name */
            display_name: string;
            /** Bio */
            bio?: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** UserStatusUpdate */
        UserStatusUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "disabled";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceListResponse */
        VoiceListResponse: {
            /** Items */
            items: components["schemas"]["VoiceSummary"][];
        };
        /** VoiceProfileCreate */
        VoiceProfileCreate: {
            /** Dataset Id */
            dataset_id: string;
            /** Display Name */
            display_name: string;
            /** Reference Name */
            reference_name?: string | null;
        };
        /** VoiceProfileResponse */
        VoiceProfileResponse: {
            /** Id */
            id: string;
            /** Dataset Id */
            dataset_id: string;
            /** Status */
            status: string;
            /**
             * Mode
             * @constant
             */
            mode: "zero_shot";
            /** Base Model Id */
            base_model_id: string;
            /** Display Name */
            display_name: string;
            /**
             * Reference Emotions
             * @default []
             */
            reference_emotions: components["schemas"]["EmotionLabel"][];
            /** Reference Snr Db */
            reference_snr_db?: number | null;
            /**
             * Quality Warning Codes
             * @default []
             */
            quality_warning_codes: string[];
            /**
             * References
             * @default []
             */
            references: components["schemas"]["VoiceReferenceItemResponse"][];
        };
        /** VoiceReferenceCreate */
        VoiceReferenceCreate: {
            /** Dataset Id */
            dataset_id: string;
            /** Reference Name */
            reference_name?: string | null;
        };
        /** VoiceReferenceItemResponse */
        VoiceReferenceItemResponse: {
            /** Id */
            id: string;
            /** Asset Id */
            asset_id: string;
            /** Segment Id */
            segment_id: string;
            /** Prompt Text */
            prompt_text: string;
            /** Prompt Language */
            prompt_language: string;
            /** Emotion Label */
            emotion_label: string;
            /** Emotion Confidence */
            emotion_confidence?: number | null;
            /** Is Primary */
            is_primary: boolean;
            /** Reference Name */
            reference_name?: string | null;
            /** Snr Db */
            snr_db?: number | null;
            /** Created At */
            created_at: string;
        };
        /** VoiceSummary */
        VoiceSummary: {
            /** Id */
            id: string;
            /** Dataset Id */
            dataset_id: string;
            /** Display Name */
            display_name: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Can Synthesize */
            can_synthesize: boolean;
            /** Mode */
            mode?: "zero_shot" | null;
            /** Base Model Id */
            base_model_id?: string | null;
            /**
             * Reference Emotions
             * @default []
             */
            reference_emotions: string[];
            /** Reference Snr Db */
            reference_snr_db?: number | null;
            /**
             * Quality Warning Codes
             * @default []
             */
            quality_warning_codes: string[];
            /**
             * References
             * @default []
             */
            references: components["schemas"]["VoiceReferenceItemResponse"][];
        };
        /** VoiceTrainRequest */
        VoiceTrainRequest: {
            /**
             * Consent Confirmed
             * @constant
             */
            consent_confirmed: true;
        };
        /** WatermarkVerificationRequest */
        WatermarkVerificationRequest: {
            /** Job Id */
            job_id: string;
        };
        /** WatermarkVerificationResponse */
        WatermarkVerificationResponse: {
            /** Job Id */
            job_id: string;
            /** Probability */
            probability: number;
            /** Payload */
            payload: number | null;
            /** Payload Matches Job */
            payload_matches_job: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    bootstrap_admin_api_admin_bootstrap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListResponse"];
                };
            };
        };
    };
    update_user_status_api_admin_users__user_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_events_api_admin_audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
                before_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    list_datasets_api_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetListResponse"];
                };
            };
        };
    };
    create_dataset_api_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_dataset_api_datasets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preprocess_dataset_api_datasets__dataset_id__preprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetPreprocessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dataset_segments_api_datasets__dataset_id__segments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_dataset_segment_api_datasets__dataset_id__segments__segment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSegmentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_dataset_segments_api_datasets__dataset_id__segments_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_voice_profiles_api_voices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceListResponse"];
                };
            };
        };
    };
    create_voice_profile_api_voices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_voice_reference_api_voices__profile_id__references_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceReferenceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_voice_reference_api_voices__profile_id__references__reference_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
                reference_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    train_voice_profile_api_voices__profile_id__train_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceTrainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_voice_profile_api_voices__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_emotion_api_datasets__dataset_id__segments__segment_id__emotion_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmotionOverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_syntheses_api_syntheses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SynthesisListResponse"];
                };
            };
        };
    };
    create_synthesis_api_syntheses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SynthesisCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SynthesisQueuedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_synthesis_api_syntheses__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SynthesisSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_synthesis_audio_api_syntheses__job_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_watermark_api_safety_detect_watermark_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatermarkVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatermarkVerificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_voice_api_voices__profile_id__evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationQueuedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_profile_api_users_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    update_my_profile_api_users_me_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_my_avatar_api_users_me_avatar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_my_avatar_api_users_me_avatar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_avatar_api_avatars__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unread_count_api_notifications_unread_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCountResponse"];
                };
            };
        };
    };
    mark_read_api_notifications_mark_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkReadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_posts_api_plaza_posts_get: {
        parameters: {
            query?: {
                mine?: boolean;
                favorited?: boolean;
                q?: string | null;
                sort?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlazaPostListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_post_api_plaza_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlazaPublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlazaPostSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_comments_api_plaza_comments_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlazaCommentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_api_plaza_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlazaPostSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_post_api_plaza_posts__post_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlazaDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_comments_api_plaza_posts__post_id__comments_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlazaCommentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_comment_api_plaza_posts__post_id__comments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlazaCommentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlazaCommentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    like_post_api_plaza_posts__post_id__likes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlazaActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlike_post_api_plaza_posts__post_id__likes_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlazaActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    favorite_post_api_plaza_posts__post_id__favorites_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlazaActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unfavorite_post_api_plaza_posts__post_id__favorites_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlazaActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_package_api_plaza_posts__post_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_reference_api_plaza_posts__post_id__download_reference_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_reference_api_plaza_posts__post_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_post_api_plaza_posts__post_id__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlazaImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlazaImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
